agents:
  simulation_monitor:
    detailed_logging: false
    enable_alerts: true
    poll_interval: 60
    script: agents.simulation_monitor
    status_file: shadow.data/monerosim_monitor.log
  user_agents:
  - attributes:
      can_receive_distributions: true
      hashrate: '100'
      is_miner: true
    daemon: monerod
    wallet: monero-wallet-rpc
    mining_script: agents.autonomous_miner
  - attributes:
      can_receive_distributions: true
      max_transaction_amount: '2.0'
      min_transaction_amount: '0.5'
      transaction_interval: '60'
    daemon: monerod
    user_script: agents.regular_user
    wallet: monero-wallet-rpc
general:
  fresh_blockchain: true
  log_level: info
  stop_time: 600s
  simulation_seed: 70542
network:
  peer_mode: Dynamic
  topology: Star
  type: 1_gbit_switch
