agents:
  user_agents:
  - attributes:
      can_receive_distributions: true
      hashrate: '10'
      is_miner: true
    count: 10
    daemon: monerod
    wallet: monero-wallet-rpc
    mining_script: agents.autonomous_miner
  - attributes:
      can_receive_distributions: false
      max_transaction_amount: '0.1'
      min_transaction_amount: '0.01'
      transaction_interval: '60'
    count: 90
    daemon: monerod
    user_script: agents.regular_user
    wallet: monero-wallet-rpc
general:
  fresh_blockchain: true
  log_level: debug
  stop_time: 1h
  simulation_seed: 45879
network:
  path: topology_1k.gml
  peer_mode: Dynamic
  topology: Star
