agents:
  user_agents:
  - attributes:
      can_receive_distributions: true
      hashrate: '5'
      is_miner: true
    count: 20
    daemon: monerod
    wallet: monero-wallet-rpc
    mining_script: agents.autonomous_miner
  - attributes:
      can_receive_distributions: false
      max_transaction_amount: '2.0'
      min_transaction_amount: '0.1'
      transaction_interval: '300'
    count: 80
    daemon: monerod
    user_script: agents.regular_user
    wallet: monero-wallet-rpc
general:
  fresh_blockchain: true
  log_level: info
  stop_time: 2h
  simulation_seed: 28281
network:
  path: examples/topology_large_2000.gml
  peer_mode: Dynamic
  topology: Mesh
